### ISSUE TITLE
does not work in go 1.18

### ISSUE THREAD

**Issue by 0wwafa** [shurcooL/goexec#11]
```
go install github.com/shurcooL/goexec@latest
go: downloading github.com/shurcooL/goexec v0.0.0-20230709021537-96bada04ea2b
go: finding module for package golang.org/x/tools/imports
go: finding module for package github.com/shurcooL/go-goon
go: downloading golang.org/x/tools v0.26.0
go: downloading github.com/shurcooL/go-goon v1.0.0
go: found github.com/shurcooL/go-goon in github.com/shurcooL/go-goon v1.0.0
go: found golang.org/x/tools/imports in golang.org/x/tools v0.26.0
go: downloading github.com/shurcooL/go v0.0.0-20200502201357-93f07166e636
go: downloading golang.org/x/mod v0.21.0
go: downloading golang.org/x/sync v0.8.0
# golang.org/x/tools/go/ast/astutil
/home/user/go/pkg/mod/golang.org/x/tools@v0.26.0/go/ast/astutil/util.go:11:48: undefined: ast.Unparen
note: module requires Go 1.22
# golang.org/x/tools/internal/gocommand
/home/user/go/pkg/mod/golang.org/x/tools@v0.26.0/internal/gocommand/invoke.go:258:6: cmd.WaitDelay undefined (type *exec.Cmd has no field or method WaitDelay)
note: module requires Go 1.22
```
